# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='фото')),
                ('first_name', models.CharField(max_length=20, verbose_name='имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='фамилия')),
                ('city', models.CharField(max_length=40, verbose_name='город')),
                ('bio', models.TextField(max_length=10000, verbose_name='биография')),
                ('donated_money', models.DecimalField(decimal_places=0, default=0, max_digits=1000000, verbose_name='пожертвованных средств')),
                ('verified', models.BooleanField(default=False, verbose_name='верифицирован')),
                ('moderated', models.BooleanField(default=False, verbose_name='проверен модераторами')),
            ],
            options={
                'verbose_name': 'персону ',
                'verbose_name_plural': 'персоны',
            },
        ),
    ]
