# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navalny_people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'человек', 'verbose_name_plural': 'люди'},
        ),
    ]
