# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navalny_people', '0003_auto_20170813_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='uid',
            field=models.CharField(default='', max_length=10),
        ),
    ]
